# SOPS configuration for dotfiles
keys:
  # Your age key
  - &mikki_key age16zj0qm6fwaffschx76vxy9qk6u6qve6r9y40xdymtmw86s8rkf8slvzf6q

creation_rules:
  # All secret files use your age key
  - path_regex: secrets/.*\.(yaml|json)$
    key_groups:
      - age:
          - *mikki_key

  # Environment-specific rules for future use
  - path_regex: secrets/development/.*\.yaml$
    key_groups:
      - age:
          - *mikki_key