# SOPS configuration for dotfiles
keys:
  # AI Development / Dotfiles key
  - &dotfiles_key age106l335mhlehuwzrmghvssa9qsqar7z008vmfg5zn8qwx4shrhy9q4jvzcj
  # OGT Web Production key
  - &ogt_key age1vt4kwwf9l5888q65szxc6dg4t3m69cu9wpx3qe400kh8e4rvyvsszrjmgq
  # SSH-derived key — bootstrap on any machine via:
  #   ssh-to-age -private-key -i ~/.ssh/id_ed25519 > ~/.config/sops/age/keys.txt
  - &ssh_key age1mch8x334rdc94fwrfmd5efchsjutv45yshh7cauew8kjgttsdycsp0uqfj

creation_rules:
  - path_regex: secrets/.*\.(yaml|json)$
    key_groups:
      - age:
          - *dotfiles_key
          - *ogt_key
          - *ssh_key

  - path_regex: .*\.env\.enc$
    key_groups:
      - age:
          - *dotfiles_key
          - *ogt_key
          - *ssh_key

  - path_regex: .*\.envrc\.enc$
    key_groups:
      - age:
          - *dotfiles_key
          - *ogt_key
          - *ssh_key

  - path_regex: secrets/development/.*\.yaml$
    key_groups:
      - age:
          - *dotfiles_key
          - *ogt_key
          - *ssh_key
