version: 3
hotkeys:
  new-tab: [Ctrl-Shift-T]
  split-right: [Ctrl-Shift-D]
  split-down: [Ctrl-D]
terminal:
  fontSize: 14
  colorScheme:
    name: Nord
    foreground: "#D8DEE9"
    background: "#2E3440"
    cursor: "#D8DEE9"
    colors:
      - "#3B4252"
      - "#BF616A"
      - "#A3BE8C"
      - "#EBCB8B"
      - "#81A1C1"
      - "#B48EAD"
      - "#88C0D0"
      - "#E5E9F0"
      - "#4C566A"
      - "#BF616A"
      - "#A3BE8C"
      - "#EBCB8B"
      - "#81A1C1"
      - "#B48EAD"
      - "#8FBCBB"
      - "#ECEFF4"
ssh:
  connections: []
profiles:
  - name: "Zellij Shared - Gateway"
    type: ssh
    options:
      host: 51.38.127.98
      port: 22
      user: mhugo
      privateKey: /home/mhugo/.ssh/id_rsa
      scripts:
        - "zellij attach shared || zellij --session shared"
  
  - name: "Zellij Work - Gateway"
    type: ssh
    options:
      host: 51.38.127.98
      port: 22
      user: mhugo
      privateKey: /home/mhugo/.ssh/id_rsa
      scripts:
        - "zellij attach work || zellij --session work"

connectionGateway:
  enabled: true
  url: ws://51.38.127.98:9000
  token: BNgh9981doggy!!

  - name: "gateway"
    host: "51.38.127.98"
    port: 22
    user: "mhugo"
    privateKey: "/home/mhugo/.ssh/id_rsa"

  - name: "test-sync"
    host: "51.38.127.98"
    port: 22
    user: "mhugo"
    privateKey: "/home/mhugo/.ssh/test_key"
