kind: pipeline
type: docker
name: deploy-dotfiles

# Triggered on push to dotfiles repo
trigger:
  branch:
    - main
  event:
    - push

steps:
  # Sync dotfiles to all servers
  - name: sync-dotfiles
    image: alpine/git
    commands:
      - git pull origin main
      - ./scripts/sync-to-servers.sh
      
  # Update Docker services if changed
  - name: update-services
    image: docker/compose
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - cd docker/tabby-admin
      - docker-compose pull
      - docker-compose up -d
    when:
      paths:
        include:
          - docker/**
          
  # Run tests
  - name: test
    image: alpine
    commands:
      - ./scripts/test-admin-stack.sh
      
  # Backup after changes
  - name: backup
    image: alpine
    commands:
      - docker exec backup /backup.sh

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: update-tabby-gateway

trigger:
  event:
    - custom
    
steps:
  - name: deploy
    image: alpine
    commands:
      - cd docker/tabby-admin
      - docker-compose up -d tabby-gateway
      
  - name: health-check
    image: alpine
    commands:
      - ./scripts/health-check.sh tabby-gateway