version: '3.8'

services:
  # HashiCorp Vault - Master secret store
  vault:
    image: vault:latest
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ports:
      - "127.0.0.1:8200:8200"
    volumes:
      - vault-data:/vault/file
      - vault-logs:/vault/logs
      - ./vault/config.hcl:/vault/config/config.hcl:ro
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_API_ADDR=http://0.0.0.0:8200
    command: server
    networks:
      - tabby-net

  # Vault auto-backup to Google Drive
  vault-backup:
    build: ./vault-backup
    container_name: vault-backup
    restart: unless-stopped
    volumes:
      - vault-data:/vault/file:ro
      - ./backups/vault:/backups
    environment:
      - BACKUP_SCHEDULE="0 */4 * * *"  # Every 4 hours
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
    depends_on:
      - vault
    networks:
      - tabby-net

  # Warpgate - Advanced SSH/HTTP bastion with web UI
  warpgate:
    image: ghcr.io/warp-tech/warpgate:latest
    container_name: warpgate
    restart: unless-stopped
    ports:
      - "127.0.0.1:8888:8888"  # Web UI
      - "127.0.0.1:2222:2222"  # SSH bastion
    volumes:
      - warpgate-data:/data
      - ./warpgate/config.yaml:/etc/warpgate.yaml:ro
    environment:
      - RUST_LOG=info
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      - tabby-net
      
  # Tabby Web - Custom build with pre-configured sessions
  tabby-web:
    build: 
      context: ./tabby-custom
      args:
        - TABBY_VERSION=v1.0.197
        - PRESET_CONFIG=admin
    container_name: tabby-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - tabby-data:/data
      - ./tabby-sessions:/sessions:ro
    environment:
      - NODE_ENV=production
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
      - warpgate
    networks:
      - tabby-net
      
  # Custom Tabby Builder
  tabby-builder:
    build: ./tabby-builder
    container_name: tabby-builder
    volumes:
      - ./builds:/output
      - ./configs:/configs:ro
    profiles:
      - build
      
  # Admin Dashboard
  admin-ui:
    build: ./admin-ui
    container_name: admin-ui
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      - SITE_TITLE=Hugo.dk Admin
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      - tabby-net
      
  # Gitea - Self-hosted Git
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - gitea-data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__server__DOMAIN=git.hugo.dk
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      - tabby-net
      
  # Drone CI
  drone:
    image: drone/drone:2
    container_name: drone
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:80"
    volumes:
      - drone-data:/data
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_SERVER_HOST=ci.hugo.dk
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - gitea
      - vault
    networks:
      - tabby-net
      
  # Nexus Docker-in-Docker with Cloudflare Tunnel
  nexus-hugo-dk:
    build: ../nexus-dind
    container_name: nexus-hugo-dk
    restart: unless-stopped
    privileged: true
    ports:
      - "2376:2376"  # Docker daemon
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - nexus-data:/var/lib/docker
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
      - DOCKER_TLS_CERTDIR=/certs
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      - tabby-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
      
  # Monitoring & Heartbeat
  monitor:
    build: ./monitor
    container_name: monitor
    restart: unless-stopped
    volumes:
      - monitor-data:/data
    environment:
      - HEARTBEAT_URL=https://admin.hugo.dk/heartbeat
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      - tabby-net
      
  # Complete backup service
  backup:
    build: ./backup
    container_name: backup
    restart: unless-stopped
    volumes:
      - vault-data:/backup/vault:ro
      - warpgate-data:/backup/warpgate:ro
      - tabby-data:/backup/tabby:ro
      - gitea-data:/backup/gitea:ro
      - drone-data:/backup/drone:ro
      - /home/mhugo/.dotfiles:/backup/dotfiles:ro
      - ./backups:/output
    environment:
      - BACKUP_SCHEDULE="0 */6 * * *"
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - VAULT_ADDR=http://vault:8200
    depends_on:
      - vault
    networks:
      - tabby-net

volumes:
  vault-data:
  vault-logs:
  warpgate-data:
  tabby-data:
  gitea-data:
  drone-data:
  monitor-data:
  nexus-data:

networks:
  tabby-net:
    driver: bridge