version: '3.8'

services:
  # Simple AI environment with pre-built images
  ai:
    image: python:3.11-slim
    container_name: nexus-ai-simple
    restart: unless-stopped
    ports:
      - "10080:8080"  # Code server
      - "10888:8888"  # Jupyter
    volumes:
      - ~/code:/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - CF_API_TOKEN=${CF_API_TOKEN}
    working_dir: /workspace
    command: >
      bash -c "
        apt-get update && apt-get install -y curl git nodejs npm &&
        curl https://mise.run | sh &&
        ~/.local/bin/mise use -g python@3.11 &&
        ~/.local/bin/mise use -g node@20 &&
        pip install aider-chat jupyter openai anthropic &&
        npm install -g @githubnext/github-copilot-cli &&
        curl -fsSL https://code-server.dev/install.sh | sh &&
        nohup code-server --bind-addr 0.0.0.0:8080 --auth none /workspace &
        nohup jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root &
        echo 'AI tools ready!' &&
        echo 'VS Code: http://localhost:10080' &&
        echo 'Jupyter: http://localhost:10888' &&
        tail -f /dev/null
      "

  # Dev Vault
  vault:
    image: vault:latest
    container_name: nexus-vault-simple
    restart: unless-stopped
    ports:
      - "10200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=nexus-dev-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    command: server -dev

volumes:
  code-workspace:
