# home/modules/stable-shell.nix
#
# Host-wide non-interactive bash for agents: jcode swarms, Cursor, Codex,
# Claude, and other coding clients. On NixOS the login SHELL often points at
# /run/current-system/sw/bin/bash; sandboxes and some user services cannot
# see /run. Point SHELL at an immutable store wrapper instead.
#
# Agent shells do not source ~/.bashrc, so interactive direnv hooks never
# fire. The wrapper sources shell/bash/direnv-export.sh: `direnv allow` then
# export, skip when IN_NIX_SHELL is already set (impure is valid). Same
# loader as zshenv, bashrc, and BASH_ENV. It also sources otel-env.sh so
# OTEL_EXPORTER_OTLP_* reaches CLI children without a login bashrc.
#
# Permanent guarantees:
# - SHELL itself is an immutable store path, so deleting or chmodding the
#   compatibility copy under ~/.local cannot prevent the next shell spawn.
# - home.file still installs executable compatibility and recovery wrappers.
# - pkgs.bashInteractive is in home.packages (gcroot; shebang survives GC).
# - login oneshot re-runs refresh after nixos-rebuild / profile churn.
# - Prefer enter-once: if IN_NIX_SHELL is already set, do not re-run direnv
#   (nested `#!/usr/bin/env bash` → this wrapper must not re-eval $PWD's flake).
# - DIRENV_DISABLE=1 is a rare escape hatch; direnv is also capped at 15s.
#
# Cursor-only: ~/.cursor/hooks/fix-stable-shell-chmod.cjs recovers when a
# Cursor agent Write replaces the wrapper with mode 644.
{
  config,
  lib,
  pkgs,
  ...
}: let
  bash = pkgs.bashInteractive;
  bashBin = "${bash}/bin/bash";
  stableBashRel = ".local/share/stable-shell/bash";

  # Shared body used by declarative wrapper, refresh script, and Node recovery hook.
  # Enter Nix once: skip direnv when already in a flake/Nix shell so nested bash
  # (repo shebang, scripts) does not cold-eval a jj worktree flake again.
  # NixOS programs.direnv owns DIRENV_CONFIG=/etc/direnv (nix-direnv 3.2.0).
  direnvInheritLines = ''
    # Same enter-once loader as zshenv, bashrc, and BASH_ENV.
    # shellcheck disable=SC1091
    [ -f "$HOME/.dotfiles/shell/bash/direnv-export.sh" ] \
      && . "$HOME/.dotfiles/shell/bash/direnv-export.sh"
  '';

  wrapperText = ''
    #!${bashBin}
    # Agent shell wrapper: sandbox-safe bash + direnv inherit for $PWD.
    # Managed by home-manager stable-shell (store shebang; never /run).
    # Enter Nix once: skip direnv when IN_NIX_SHELL is already set.
    # Escape: DIRENV_DISABLE=1. Direnv is also capped at 15s.
    _stable_shell_caller_path="$PATH"
    if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
      unset __HM_SESS_VARS_SOURCED
      # shellcheck disable=SC1091
      . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi
    IFS=: read -r -a _stable_shell_path_entries <<< "$_stable_shell_caller_path:$PATH"
    PATH=""
    _stable_shell_seen=":"
    for _stable_shell_entry in "''${_stable_shell_path_entries[@]}"; do
      [[ -n "$_stable_shell_entry" ]] || continue
      case "$_stable_shell_seen" in
        *":$_stable_shell_entry:"*) ;;
        *)
          PATH="''${PATH:+$PATH:}$_stable_shell_entry"
          _stable_shell_seen="$_stable_shell_seen$_stable_shell_entry:"
          ;;
      esac
    done
    export PATH
    unset _stable_shell_caller_path _stable_shell_path_entries _stable_shell_seen _stable_shell_entry
    # Agent shells skip ~/.bashrc; load CentralCloud OTLP the same way login shells do.
    # shellcheck disable=SC1091
    [ -f "$HOME/.dotfiles/shell/bash/otel-env.sh" ] && . "$HOME/.dotfiles/shell/bash/otel-env.sh"
    ${direnvInheritLines}
    exec ${bashBin} "$@"
  '';

  # This path is the bootstrap authority. Agents can spawn it without /run and
  # no mutable file under HOME must exist before the shell starts.
  storeBash = pkgs.writeTextFile {
    name = "agent-shell";
    executable = true;
    text = wrapperText;
  };

  refreshScript = ''
    #!${bashBin}
    set -euo pipefail
    STABLE="''${XDG_DATA_HOME:-$HOME/.local/share}/stable-shell/bash"
    PINNED="${bashBin}"
    mkdir -p "$(dirname "$STABLE")" "$HOME/.local/bin" \
      "''${XDG_DATA_HOME:-$HOME/.local/share}/gcroots"
    target=""
    for candidate in \
      "$HOME/.nix-profile/bin/bash" \
      /run/current-system/sw/bin/bash \
      "$PINNED"
    do
      if [[ -x "$candidate" ]]; then
        resolved=$(${pkgs.coreutils}/bin/readlink -f "$candidate" 2>/dev/null || printf '%s' "$candidate")
        [[ -x "$resolved" ]] || continue
        case "$resolved" in
          /run/*) continue ;;
        esac
        target=$resolved
        break
      fi
    done
    if [[ -z "$target" ]]; then
      echo "refresh-stable-shell: no store bash candidate found" >&2
      exit 1
    fi
    {
      printf '%s\n' "#!$target"
      printf '%s\n' "# Agent shell wrapper: sandbox-safe bash + direnv inherit for \$PWD."
      printf '%s\n' "# Regenerated by ~/.local/bin/refresh-stable-shell (home-manager stable-shell)."
      printf '%s\n' "# Enter Nix once: skip direnv when IN_NIX_SHELL is already set."
      printf '%s\n' "# Escape: DIRENV_DISABLE=1. Direnv is also capped at 15s."
      printf '%s\n' '_stable_shell_caller_path="$PATH"'
      printf '%s\n' 'if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then'
      printf '%s\n' '  unset __HM_SESS_VARS_SOURCED'
      printf '%s\n' '  # shellcheck disable=SC1091'
      printf '%s\n' '  . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"'
      printf '%s\n' 'fi'
      printf '%s\n' 'IFS=: read -r -a _stable_shell_path_entries <<< "$_stable_shell_caller_path:$PATH"'
      printf '%s\n' 'PATH=""'
      printf '%s\n' '_stable_shell_seen=":"'
      printf '%s\n' 'for _stable_shell_entry in "''${_stable_shell_path_entries[@]}"; do'
      printf '%s\n' '  [[ -n "$_stable_shell_entry" ]] || continue'
      printf '%s\n' '  case "$_stable_shell_seen" in'
      printf '%s\n' '    *":$_stable_shell_entry:"*) ;;'
      printf '%s\n' '    *) PATH="''${PATH:+$PATH:}$_stable_shell_entry"; _stable_shell_seen="$_stable_shell_seen$_stable_shell_entry:" ;;'
      printf '%s\n' '  esac'
      printf '%s\n' 'done'
      printf '%s\n' 'export PATH'
      printf '%s\n' 'unset _stable_shell_caller_path _stable_shell_path_entries _stable_shell_seen _stable_shell_entry'
      printf '%s\n' '# Agent shells skip ~/.bashrc; load CentralCloud OTLP env.'
      printf '%s\n' '# shellcheck disable=SC1091'
      printf '%s\n' '[ -f "$HOME/.dotfiles/shell/bash/otel-env.sh" ] && . "$HOME/.dotfiles/shell/bash/otel-env.sh"'
      printf '%s\n' '[ -f "$HOME/.dotfiles/shell/bash/direnv-export.sh" ] && . "$HOME/.dotfiles/shell/bash/direnv-export.sh"'
      printf '%s\n' "exec \"$target\" \"\$@\""
    } > "$STABLE.tmp"
    ${pkgs.coreutils}/bin/chmod 0755 "$STABLE.tmp"
    ${pkgs.coreutils}/bin/mv -f "$STABLE.tmp" "$STABLE"
    ${pkgs.coreutils}/bin/ln -sfn "$STABLE" "$HOME/.local/bin/bash"
    pkg=$(${pkgs.coreutils}/bin/dirname "$(${pkgs.coreutils}/bin/dirname "$target")")
    ${pkgs.coreutils}/bin/ln -sfn "$pkg" \
      "''${XDG_DATA_HOME:-$HOME/.local/share}/gcroots/bash-interactive"
    echo "stable-shell -> wrapper around $target (direnv once if needed; skip when IN_NIX_SHELL; mode 0755)"
  '';

  # CommonJS (.cjs): Node 24 treats .mjs as ESM and rejects require().
  hookCjsText = ''
    #!/usr/bin/env node
    "use strict";
    const fs = require("node:fs");
    const path = require("node:path");
    const home = process.env.HOME || "${config.home.homeDirectory}";
    const stable = path.join(home, ".local/share/stable-shell/bash");
    const localBin = path.join(home, ".local/bin/bash");
    const refresh = path.join(home, ".local/bin/refresh-stable-shell");
    const bashStore = "${bashBin}";
    const out = path.join(home, ".cursor/tmp/stable-shell-hook.out");
    const wrapper = [
      "#!" + bashStore,
      "# Agent shell wrapper (HM + Node hook).",
      "# Enter Nix once: skip direnv when IN_NIX_SHELL is already set.",
      "# Escape: DIRENV_DISABLE=1. Direnv is also capped at 15s.",
      '_stable_shell_caller_path="$PATH"',
      'if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then',
      "  unset __HM_SESS_VARS_SOURCED",
      '  . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"',
      "fi",
      'IFS=: read -r -a _stable_shell_path_entries <<< "$_stable_shell_caller_path:$PATH"',
      'PATH=""',
      '_stable_shell_seen=":"',
      'for _stable_shell_entry in "''${_stable_shell_path_entries[@]}"; do',
      '  [[ -n "$_stable_shell_entry" ]] || continue',
      '  case "$_stable_shell_seen" in',
      '    *":$_stable_shell_entry:"*) ;;',
      '    *) PATH="''${PATH:+$PATH:}$_stable_shell_entry"; _stable_shell_seen="$_stable_shell_seen$_stable_shell_entry:" ;;',
      "  esac",
      "done",
      "export PATH",
      "unset _stable_shell_caller_path _stable_shell_path_entries _stable_shell_seen _stable_shell_entry",
      '# Agent shells skip ~/.bashrc; load CentralCloud OTLP env.',
      '[ -f "$HOME/.dotfiles/shell/bash/otel-env.sh" ] && . "$HOME/.dotfiles/shell/bash/otel-env.sh"',
      '[ -f "$HOME/.dotfiles/shell/bash/direnv-export.sh" ] && . "$HOME/.dotfiles/shell/bash/direnv-export.sh"',
      'exec ' + bashStore + ' "$@"',
      "",
    ].join("\n");
    function log(line) {
      try {
        fs.mkdirSync(path.dirname(out), { recursive: true });
        fs.appendFileSync(out, new Date().toISOString() + " " + line + "\n");
      } catch (_) {}
    }
    try {
      fs.mkdirSync(path.dirname(stable), { recursive: true });
      fs.writeFileSync(stable, wrapper, { mode: 0o755 });
      fs.chmodSync(stable, 0o755);
      try { fs.unlinkSync(localBin); } catch (_) {}
      fs.symlinkSync(stable, localBin);
      if (fs.existsSync(refresh)) fs.chmodSync(refresh, 0o755);
      log("rewrote+chmod 0755 " + stable);
    } catch (e) {
      log("error: " + e.message);
    }
    process.stdout.write(JSON.stringify({ continue: true }));
  '';
in {
  # Single `home = { ... }` — statix forbids repeated `home.*` keys.
  home = {
    packages = [bash];

    sessionVariables.SHELL = storeBash;

    # Declarative executable wrapper — every `home-manager switch` resets +x.
    # Agents must never Write this path: a mode-644 overwrite makes agent
    # Shell fail with spawn EACCES until refresh-stable-shell / chmod 0755.
    file = {
      ${stableBashRel} = {
        executable = true;
        force = true;
        text = wrapperText;
      };

      ".local/bin/bash" = {
        executable = true;
        force = true;
        text = wrapperText;
      };

      ".local/bin/refresh-stable-shell" = {
        executable = true;
        force = true;
        text = refreshScript;
      };

      # Cursor Agent recovery: Node hook can chmod without spawning $SHELL (chicken/egg).
      # Use .cjs — Node 24 rejects require() inside .mjs (ESM).
      ".cursor/hooks/fix-stable-shell-chmod.cjs" = {
        executable = true;
        force = true;
        text = hookCjsText;
      };

      # Compat shim: old hooks.json entries pointing at .mjs still work.
      # Absolute HOME path — HM places .mjs/.cjs in separate store derivations, so
      # a relative ./fix-….cjs next to the .mjs store path does not exist.
      ".cursor/hooks/fix-stable-shell-chmod.mjs" = {
        executable = true;
        force = true;
        text = ''
          #!/usr/bin/env node
          // Deprecated shim — prefer fix-stable-shell-chmod.cjs.
          import { createRequire } from "node:module";
          import { join } from "node:path";
          import { homedir } from "node:os";
          createRequire(import.meta.url)(
            join(homedir(), ".cursor/hooks/fix-stable-shell-chmod.cjs"),
          );
        '';
      };

      # Merge-friendly stub: operators still own full hooks.json; document required entry.
      ".cursor/hooks/stable-shell-README.md" = {
        force = true;
        text = ''
          # Cursor recovery for the shared agent stable-shell

          The wrapper is host-wide (`~/.local/share/stable-shell/bash`). This
          Cursor hook only recovers when a Cursor agent Write replaces it with
          mode 644.

          Ensure `~/.cursor/hooks.json` (or project `.cursor/hooks.json`) includes:

          ```json
          {
            "hooks": {
              "sessionStart": [{ "command": "node $HOME/.cursor/hooks/fix-stable-shell-chmod.cjs", "timeout": 10 }],
              "afterFileEdit": [{ "command": "node $HOME/.cursor/hooks/fix-stable-shell-chmod.cjs", "timeout": 10 }]
            }
          }
          ```

          Enter Nix once via `shell/bash/direnv-export.sh` (direnv allow +
          export; skip when `IN_NIX_SHELL` is set — impure is valid). jcode
          swarms, Cursor `zsh -c`, bashrc, BASH_ENV, and this wrapper all
          source that file. Escape hatch: `DIRENV_DISABLE=1`.
        '';
      };
    };

    activation.refreshStableShell = lib.hm.dag.entryAfter ["writeBoundary"] ''
      $DRY_RUN_CMD ${config.home.homeDirectory}/.local/bin/refresh-stable-shell \
        || $DRY_RUN_CMD ${bashBin} -c ${lib.escapeShellArg refreshScript}
    '';
  };

  # Re-apply after login (nixos-rebuild without immediate hms).
  systemd.user.services.refresh-stable-shell = {
    Unit = {
      Description = "Refresh agent stable-shell bash wrapper (store shebang + chmod)";
      After = ["default.target"];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${config.home.homeDirectory}/.local/bin/refresh-stable-shell";
      RemainAfterExit = true;
    };
    Install.WantedBy = ["default.target"];
  };

  xdg.configFile."environment.d/90-stable-shell.conf" = {
    text = ''
      # NixOS /run may be hidden; jcode and other user services use this SHELL.
      SHELL=${storeBash}
    '';
    force = true;
  };
}
