# home/modules/stable-shell.nix
#
# Host-wide non-interactive bash for agents: jcode swarms, Cursor, Codex,
# Claude, and other coding clients. On NixOS the login SHELL often points at
# /run/current-system/sw/bin/bash; sandboxes and some user services cannot
# see /run. Point SHELL at an immutable store wrapper instead.
#
# Agent shells do not source ~/.bashrc, so interactive direnv hooks never
# fire. The wrapper exports BASH_ENV and the real non-interactive bash sources
# shell/bash/noninteractive-path.sh exactly once. It also sources otel-env.sh
# so OTEL_EXPORTER_OTLP_* reaches CLI children without a login bashrc.
#
# Permanent guarantees:
# - SHELL itself is an immutable store path, so deleting or chmodding the
#   compatibility copy under ~/.local cannot prevent the next shell spawn.
# - home.file still installs executable compatibility and recovery wrappers.
# - pkgs.bashInteractive is in home.packages (gcroot; shebang survives GC).
# - login oneshot re-runs refresh after nixos-rebuild / profile churn.
# - Prefer enter-once: if IN_NIX_SHELL is already set, do not re-run direnv
#   (nested `#!/usr/bin/env bash` → this wrapper must not re-eval $PWD's flake).
# - DIRENV_DISABLE=1 is a rare escape hatch; direnv is also capped at 15s.
{
  config,
  lib,
  pkgs,
  ...
}: let
  bash = pkgs.bashInteractive;
  bashBin = "${bash}/bin/bash";
  stableBashRel = ".local/share/stable-shell/bash";

  # Shared body used by declarative wrapper and refresh script.
  # Enter Nix once: skip direnv when already in a flake/Nix shell so nested bash
  # (repo shebang, scripts) does not cold-eval a jj worktree flake again.
  # NixOS programs.direnv owns DIRENV_CONFIG=/etc/direnv (nix-direnv 3.2.0).
  bashEnvLines = ''
    # The real bash sources the non-interactive loader once after this wrapper
    # execs it. Do not source direnv-export.sh in both layers.
    export BASH_ENV="$HOME/.dotfiles/shell/bash/noninteractive-path.sh"
  '';

  wrapperText = ''
    #!${bashBin}
    # Agent shell wrapper: sandbox-safe bash + one BASH_ENV direnv entry.
    # Managed by home-manager stable-shell (store shebang; never /run).
    # Enter Nix once: skip direnv when IN_NIX_SHELL is already set.
    # Escape: DIRENV_DISABLE=1. Direnv is also capped at 15s.
    _stable_shell_caller_path="$PATH"
    if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
      unset __HM_SESS_VARS_SOURCED
      # shellcheck disable=SC1091
      . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
    fi
    IFS=: read -r -a _stable_shell_path_entries <<< "$_stable_shell_caller_path:$PATH"
    PATH=""
    _stable_shell_seen=":"
    for _stable_shell_entry in "''${_stable_shell_path_entries[@]}"; do
      [[ -n "$_stable_shell_entry" ]] || continue
      case "$_stable_shell_seen" in
        *":$_stable_shell_entry:"*) ;;
        *)
          PATH="''${PATH:+$PATH:}$_stable_shell_entry"
          _stable_shell_seen="$_stable_shell_seen$_stable_shell_entry:"
          ;;
      esac
    done
    export PATH
    unset _stable_shell_caller_path _stable_shell_path_entries _stable_shell_seen _stable_shell_entry
    # Agent shells skip ~/.bashrc; load CentralCloud OTLP the same way login shells do.
    # shellcheck disable=SC1091
    [ -f "$HOME/.dotfiles/shell/bash/otel-env.sh" ] && . "$HOME/.dotfiles/shell/bash/otel-env.sh"
    ${bashEnvLines}
    exec ${bashBin} "$@"
  '';

  # This path is the bootstrap authority. Agents can spawn it without /run and
  # no mutable file under HOME must exist before the shell starts.
  storeBash = pkgs.writeTextFile {
    name = "agent-shell";
    executable = true;
    text = wrapperText;
  };

  refreshScript = ''
    #!${bashBin}
    set -euo pipefail
    STABLE="''${XDG_DATA_HOME:-$HOME/.local/share}/stable-shell/bash"
    PINNED="${bashBin}"
    mkdir -p "$(dirname "$STABLE")" "$HOME/.local/bin" \
      "''${XDG_DATA_HOME:-$HOME/.local/share}/gcroots"
    target=""
    for candidate in \
      "$HOME/.nix-profile/bin/bash" \
      /run/current-system/sw/bin/bash \
      "$PINNED"
    do
      if [[ -x "$candidate" ]]; then
        resolved=$(${pkgs.coreutils}/bin/readlink -f "$candidate" 2>/dev/null || printf '%s' "$candidate")
        [[ -x "$resolved" ]] || continue
        case "$resolved" in
          /run/*) continue ;;
        esac
        target=$resolved
        break
      fi
    done
    if [[ -z "$target" ]]; then
      echo "refresh-stable-shell: no store bash candidate found" >&2
      exit 1
    fi
    {
      printf '%s\n' "#!$target"
      printf '%s\n' "# Agent shell wrapper: sandbox-safe bash + one BASH_ENV direnv entry."
      printf '%s\n' "# Regenerated by ~/.local/bin/refresh-stable-shell (home-manager stable-shell)."
      printf '%s\n' "# Enter Nix once: skip direnv when IN_NIX_SHELL is already set."
      printf '%s\n' "# Escape: DIRENV_DISABLE=1. Direnv is also capped at 15s."
      printf '%s\n' '_stable_shell_caller_path="$PATH"'
      printf '%s\n' 'if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then'
      printf '%s\n' '  unset __HM_SESS_VARS_SOURCED'
      printf '%s\n' '  # shellcheck disable=SC1091'
      printf '%s\n' '  . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"'
      printf '%s\n' 'fi'
      printf '%s\n' 'IFS=: read -r -a _stable_shell_path_entries <<< "$_stable_shell_caller_path:$PATH"'
      printf '%s\n' 'PATH=""'
      printf '%s\n' '_stable_shell_seen=":"'
      printf '%s\n' 'for _stable_shell_entry in "''${_stable_shell_path_entries[@]}"; do'
      printf '%s\n' '  [[ -n "$_stable_shell_entry" ]] || continue'
      printf '%s\n' '  case "$_stable_shell_seen" in'
      printf '%s\n' '    *":$_stable_shell_entry:"*) ;;'
      printf '%s\n' '    *) PATH="''${PATH:+$PATH:}$_stable_shell_entry"; _stable_shell_seen="$_stable_shell_seen$_stable_shell_entry:" ;;'
      printf '%s\n' '  esac'
      printf '%s\n' 'done'
      printf '%s\n' 'export PATH'
      printf '%s\n' 'unset _stable_shell_caller_path _stable_shell_path_entries _stable_shell_seen _stable_shell_entry'
      printf '%s\n' '# Agent shells skip ~/.bashrc; load CentralCloud OTLP env.'
      printf '%s\n' '# shellcheck disable=SC1091'
      printf '%s\n' '[ -f "$HOME/.dotfiles/shell/bash/otel-env.sh" ] && . "$HOME/.dotfiles/shell/bash/otel-env.sh"'
      printf '%s\n' 'export BASH_ENV="$HOME/.dotfiles/shell/bash/noninteractive-path.sh"'
      printf '%s\n' "exec \"$target\" \"\$@\""
    } > "$STABLE.tmp"
    ${pkgs.coreutils}/bin/chmod 0755 "$STABLE.tmp"
    ${pkgs.coreutils}/bin/mv -f "$STABLE.tmp" "$STABLE"
    ${pkgs.coreutils}/bin/ln -sfn "$STABLE" "$HOME/.local/bin/bash"
    pkg=$(${pkgs.coreutils}/bin/dirname "$(${pkgs.coreutils}/bin/dirname "$target")")
    ${pkgs.coreutils}/bin/ln -sfn "$pkg" \
      "''${XDG_DATA_HOME:-$HOME/.local/share}/gcroots/bash-interactive"
    echo "stable-shell -> wrapper around $target (direnv delegated once to BASH_ENV; mode 0755)"
  '';
in {
  # Single `home = { ... }` — statix forbids repeated `home.*` keys.
  home = {
    packages = [bash];

    sessionVariables.SHELL = storeBash;

    # Declarative executable wrapper — every `home-manager switch` resets +x.
    # Agents must never Write this path: a mode-644 overwrite makes agent
    # Shell fail with spawn EACCES until refresh-stable-shell / chmod 0755.
    file = {
      ${stableBashRel} = {
        executable = true;
        force = true;
        text = wrapperText;
      };

      ".local/bin/bash" = {
        executable = true;
        force = true;
        text = wrapperText;
      };

      ".local/bin/refresh-stable-shell" = {
        executable = true;
        force = true;
        text = refreshScript;
      };
    };

    activation.refreshStableShell = lib.hm.dag.entryAfter ["writeBoundary"] ''
      $DRY_RUN_CMD ${config.home.homeDirectory}/.local/bin/refresh-stable-shell \
        || $DRY_RUN_CMD ${bashBin} -c ${lib.escapeShellArg refreshScript}
    '';
  };

  # Re-apply after login (nixos-rebuild without immediate hms).
  systemd.user.services.refresh-stable-shell = {
    Unit = {
      Description = "Refresh agent stable-shell bash wrapper (store shebang + chmod)";
      After = ["default.target"];
    };
    Service = {
      Type = "oneshot";
      ExecStart = "${config.home.homeDirectory}/.local/bin/refresh-stable-shell";
      RemainAfterExit = true;
    };
    Install.WantedBy = ["default.target"];
  };

  xdg.configFile."environment.d/90-stable-shell.conf" = {
    text = ''
      # NixOS /run may be hidden; jcode and other user services use this SHELL.
      SHELL=${storeBash}
    '';
    force = true;
  };
}
