eval "$(direnv hook bash)"
# Nix daemon setup
if [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ]; then
  . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
fi
export PATH="$HOME/.local/bin:$PATH"

# Auto-start GitHub Actions runner
# source /home/mhugo/code/singularity/scripts/autostart-runner.sh
. "/home/mhugo/.cache/singularity/cargo/env"
