#\!/bin/bash
echo "🔄 Ways to reload environment:"
echo ""
echo "1. Quick reload (current shell):"
echo "   source ~/.bashrc"
echo ""
echo "2. New shell session:"
echo "   exec bash"
echo ""
echo "3. Full logout/login:"
echo "   exit (then SSH back in)"
echo ""
echo "Current environment status:"
echo "GITHUB_TOKEN: ${GITHUB_TOKEN:+✅ Set (${GITHUB_TOKEN:0:10}...)}"
echo "OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:+✅ Set}"
echo "GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY:+✅ Set}"

