version: '3.8'

services:
  # Vector Database for RAG
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant-storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
    ports:
      - "16333:6333"
      - "16334:6334"
    networks:
      - admin-net

  # ChromaDB - Alternative vector store
  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    restart: unless-stopped
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
      - ANONYMIZED_TELEMETRY=FALSE
    ports:
      - "18000:8000"
    networks:
      - admin-net

  # LlamaIndex Service
  llamaindex:
    build:
      context: ./llamaindex
      dockerfile: Dockerfile
    container_name: llamaindex
    restart: unless-stopped
    volumes:
      - code-workspace:/workspace:ro
      - index-data:/index
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - CHROMA_URL=http://chroma:8000
    networks:
      - admin-net
    depends_on:
      - qdrant
      - chroma

  # Enhanced Aider with RAG
  aider-rag:
    build:
      context: ./aider-rag
      dockerfile: Dockerfile
    container_name: aider-rag
    restart: unless-stopped
    volumes:
      - code-workspace:/workspace
      - ~/.gitconfig:/root/.gitconfig:ro
      - ~/.ssh:/root/.ssh:ro
      - dind-certs-client:/certs/client:ro
      - index-data:/index:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DOCKER_HOST=tcp://dind:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_CERT_PATH=/certs/client
      - QDRANT_URL=http://qdrant:6333
      - CHROMA_URL=http://chroma:8000
      - RAG_ENABLED=true
    command: ["--architect", "--no-auto-commits"]
    networks:
      - admin-net
    depends_on:
      - dind
      - qdrant
      - llamaindex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aider-rag.rule=Host(`aider-rag.nexus.hugo.dk`)"
      - "traefik.http.services.aider-rag.loadbalancer.server.port=8080"

  # Code search and indexing service
  sourcegraph:
    image: sourcegraph/server:latest
    container_name: sourcegraph
    restart: unless-stopped
    volumes:
      - sourcegraph-config:/etc/sourcegraph
      - sourcegraph-data:/var/opt/sourcegraph
      - code-workspace:/workspace:ro
    environment:
      - SOURCEGRAPH_EXTERNAL_URL=https://search.nexus.hugo.dk
    ports:
      - "7080:7080"
    networks:
      - admin-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sourcegraph.rule=Host(`search.nexus.hugo.dk`)"
      - "traefik.http.services.sourcegraph.loadbalancer.server.port=7080"

  # Embedding service for code
  embedding-service:
    build:
      context: ./embedding
      dockerfile: Dockerfile
    container_name: embedding-service
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL=text-embedding-3-small
    ports:
      - "8001:8001"
    networks:
      - admin-net

volumes:
  qdrant-storage:
  chroma-data:
  index-data:
  sourcegraph-config:
  sourcegraph-data:

networks:
  admin-net:
    external: true
    name: tabby-admin_default