# Pre-configured Tabby sessions for admin environment
# These auto-load when Tabby starts

profiles:
  - id: warpgate-ssh
    name: "Warpgate SSH"
    type: ssh
    icon: fas fa-shield-alt
    options:
      host: localhost
      port: 2222
      username: admin
      
  - id: local-gitea
    name: "Gitea"
    type: local
    icon: fas fa-code-branch
    options:
      command: docker exec -it gitea bash
      
  - id: drone-logs
    name: "CI Logs"
    type: local
    icon: fas fa-tasks
    options:
      command: docker logs -f drone
      
sessions:
  # Admin layout - auto-opens on start
  - name: "Admin Dashboard"
    layout:
      type: split
      direction: vertical
      ratio: 0.7
      children:
        - type: split
          direction: horizontal
          ratio: 0.5
          children:
            - type: tab
              title: "Warpgate"
              profile: warpgate-ssh
            - type: tab
              title: "Gitea"
              profile: local-gitea
        - type: tab
          title: "Logs"
          profile: drone-logs
          
  # Development layout
  - name: "Development"
    layout:
      type: tab
      children:
        - title: "Editor"
          command: hx
        - title: "Terminal"
          command: /bin/bash
        - title: "Git"
          command: gitui
          
# Hotkeys
hotkeys:
  - key: "Ctrl+Shift+A"
    action: "new-tab"
    profile: "warpgate-ssh"
    
  - key: "Ctrl+Shift+G"
    action: "new-tab"
    profile: "local-gitea"
    
  - key: "Ctrl+Shift+L"
    action: "split-right"
    profile: "drone-logs"