[tools]
codex = "0.132.0"
"github:vinhnx/vtcode" = "0.105.6"
flyctl = "latest"
"go:github.com/charmbracelet/crush" = "latest"
node = "26"
"npm:@github/copilot" = "1.0.47"
gcloud = "568.0.0"
"npm:firebase-tools" = "13.35.0"
python = "3.12.12"
pulumi = "latest"
java = "21.0.2"
